src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_State__c</fullName>
        <label>Invoice State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>invoice_City__c</fullName>
        <label>invoice City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Invoice.cls
public class Invoice {
	public String name {
		get; set;
	}
 public Invoice__c invoice {
 	get; set;
 }
    
    public Opportunity opp {
        get; set;
    }
    
    public String city{
        get; set;
    }
    
    public String state{
        get; set;
    }
    
     public String zip{
        get; set;
    }
     public String streetAddress{
        get; set;
    }
    
 public Invoice() {  
  opp = [select id, account.name, account.BillingAddress, account.id from opportunity where id='00661000005urHH']; 
 // acc = [select Account from Opportunity where id = '00661000005urHH'];
  system.debug('name invoice ' + opp.account.name);
     state = opp.account.BillingAddress.getState();
     city = opp.account.BillingAddress.getCity();
     zip = opp.account.BillingAddress.getPostalCode();
     streetAddress = opp.account.BillingAddress.getStreet();
     system.debug('address ' + opp.account.BillingAddress.getState() + state + city+zip+streetAddress);
     system.debug('id ' + opp.account.id);
    
 }
 public PageReference save() {
     System.debug('state :: ' + state);
     Invoice__c invoice = new Invoice__c(
     	invoice_City__c = city,
        Invoice_State__c = state
        //Opportunity = opp
     );
  insert invoice;
  return null;
 }
    
    public list<account> getAccounts(){	    
	    List<Account> acc = [select id, name from account limit 10];       
	    return acc;
	}
}